var user = [
  {
  "login": "jisaacks",
  "id": 1355481,
  "avatar_url": "https://avatars.githubusercontent.com/u/1355481?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jisaacks",
  "html_url": "https://github.com/jisaacks",
  "followers_url": "https://api.github.com/users/jisaacks/followers",
  "following_url": "https://api.github.com/users/jisaacks/following{/other_user}",
  "gists_url": "https://api.github.com/users/jisaacks/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jisaacks/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jisaacks/subscriptions",
  "organizations_url": "https://api.github.com/users/jisaacks/orgs",
  "repos_url": "https://api.github.com/users/jisaacks/repos",
  "events_url": "https://api.github.com/users/jisaacks/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jisaacks/received_events",
  "type": "User",
  "site_admin": false,
  "name": "JD Isaacks",
  "company": "The Iron Yard",
  "blog": "http://www.jisaacks.com",
  "location": "Atlanta, GA",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 66,
  "public_gists": 13,
  "followers": 48,
  "following": 15,
  "created_at": "2012-01-19T21:09:15Z",
  "updated_at": "2015-02-27T21:13:16Z"
  }
]